name: Build and Copy Executable

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install lfs
      run: git lfs install
    - name: Track the executable
      run: git lfs track "GesturePal"
    - name: Grant execute permission
      run: chmod +x ./build.sh
    - name: Build executable 
      run: |
        ./build.sh
    - name: Push to public repo
      run: |
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_USEREMAIL }}"
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GIT_USERNAME }}/gesturepal.github.io.git
        cp dist/GesturePal gesturepal.github.io/
        cd gesturepal.github.io
        git add .
        git commit -m "Update executable"
        git push
      