name: Build and Copy Executable

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Grant execute permission
      run: chmod +x ./build.sh
    - name: Build executable 
      run: |
        ./build.sh
        ls -la 
        ls -la dist
    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

    - name: Create Release and Upload Executable
      run: |
        gh release create v1.0.0 dist/GesturePal --repo ${{ secrets.GIT_USERNAME }}/gesturepal.github.io --title "Release v1.0.0" --notes "Automated release from GitHub Actions."

        git push
      