name: Build and Push

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Grant execute permission
      run: chmod +x ./build.sh
    - name: Build executable 
      run: |
        ./build.sh
        ls -la 
        ls -la dist

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

    - name: Create Release and Upload Executable
      run: |
        gh release create v1.1.0 dist/GesturePal --repo github.com/${{ secrets.GIT_USERNAME }}/gesturepal.github.io --title "Release v1.1.0" --notes "Automated release from GitHub Actions."

        git push
      